#! /bin/bash


# docker run -it --rm -p 4000:4000 hakodocs bundle exec jekyll serve --host 0.0.0.0

docker run -it --rm \
  -p 4000:4000 \
  -v "$PWD:/srv/jekyll" \
  hakodocs \
  bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling
